# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc17e4134077ef83416b9b9d41c812cdce3282ad5cc9898dab24f2a37f399486c4cfe727337adc2c3836885eafe9f2ffa848292dd64dd93c4081f5b8f9112361

test:
  secret_key_base: 1213f97aa39141c41bcce3ced96fcf6b0ffbd80454611cba5c5febb5416c7a1f9c0e0295805d81534d10e44b563e767da6a2b3955c2cb5d3274cf2058b53d3e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
